SET REDISTOGO_URL=redis://redistogo:cdc1c4f5a4f9ea8429387f63eadbccdf@hoki.redistogo.com:10765/
SET UITEST_BROWSER=Chrome
SET UITEST_BROWSER_VERSION=50
SET UITEST_OS=Windows
SET UITEST_OS_VERSION=10
SET UITEST_RESOLUTION=1680x1050
SET UITEST_USERNAME=nickzdunic1
SET UITEST_ACCESS_KEY=X2TNDQLdgzLN4ozDEpeC
SET UITEST_SERVER=http://hub.browserstack.com/wd/hub
SET UITEST_LOCAL_TEST=true
SET UITEST_DEBUG=true
SET TEAMZONE_URL=http://localhost:3000
node node_modules\\mocha\\bin\\_mocha -t 20000 %1