// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see http://docs.c9.io:8080/#!/api/run-method-run
{
    "cmd" : [
        "bash",
        "--login",
        "-c",
        "rm $file_base_name'.js';tsc --sourcemap --module commonjs $file; mocha test/$file_base_name'Tests.js'"],
    "info" : "Compiling Typescript file $file",
    "env" : {},
    "selector" : "source.ts"
}